#!/bin/bash

ROOT=`mktemp -d --tmp=.`
eval ROOT=$ROOT

echo $ROOT
echo

./scripts/make-tarball
echo -e "\nTarball OK\n"

mv antpm_*.orig.tar.xz $ROOT/

( cd $ROOT;
    mkdir build;
    cd build
    tar --xz -xf ../antpm*.tar.xz
    mv scripts/debian .
    echo -e "\nStarting to build...\n"
    debuild -us -uc && echo -e "\nBuild OK\ndeb package in '${ROOT}' \n";
)




