.\" -*- coding: utf-8-unix -*-
.\" groff -man -Tutf8 antpm-downloader.1
.\" Copyright © 2013 by Kristóf Ralovich
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" License.
.\"
.TH ANTPM-USBMON2ANT "1" "October 2013" "antpm-usbmon2ant v1.9" "User Commands"
.SH NAME
antpm-usbmon2ant \- Tool to convert ANT USB traffic traces
.SH DESCRIPTION
.SS "Allowed options:"
.TP
\fB\-h\fR [ \fB\-\-help\fR ]
produce help message
.TP
\fB\-o\fR [ \fB\-\-op\fR ] arg (=parse) possible modes of operation:
parse|dump|usbmon|filter|count
.TP
\fB\-P\fR [ \fB\-\-input\-file\fR ]
input file, if not given reads from standard input
.TP
\fB\-V\fR [ \fB\-\-version\fR ]
Print version information
.SH "AUTHOR"
.B antpm-downloader
was written by Kristóf Ralovich. This man page is Copyright ©
2010-2013 Kristóf Ralovich.
.SH "SEE ALSO"
.UR "http://code.google.com/p/antpm"
.BR "http://code.google.com/p/antpm"
