name: Coverity Scan

# We only want to test official release code, not every pull request.
on:
  push:
    branches: [main, coverity-2024]

jobs:
  coverity:
    runs-on: ubuntu-20.04
    steps:
    - name: Install APT build-deps
      if: runner.os == 'Linux'
      run: sudo apt-get install -y pkg-config libusb-1.0-0-dev libxml2-dev libboost-dev libboost-exception-dev libboost-filesystem-dev libboost-program-options-dev libboost-test-dev  valgrind

    - uses: actions/checkout@v3

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}}/src -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_BOOST_TEST=TRUE -DUSE_GANT=TRUE

    - uses: vapier/coverity-scan-action@v1
      with:
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
        working-directory: ${{github.workspace}}/build

    - name: Coverity Build Log
      run: cat ${{github.workspace}}/build/cov-int/build-log.txt

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: coverity-report
        path: ${{github.workspace}}/build/cov-int.tgz
