name: QEMU to run BigEndian s390x Linux

on:
  push:
  workflow_dispatch:

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Setup multiarch/qemu-user-static
  #     run: |
  #       docker run --rm --privileged multiarch/qemu-user-static:register --reset
  #   - name: s390x-linux
  #     #uses: docker://multiarch/ubuntu-core:s390x-focal
  #     uses: docker://s390x/ubuntu:latest
  #     with:
  #       args: >
  #         bash -c
  #         "uname -a &&
  #         lscpu | grep Endian &&
  #         apt-get -y update &&
  #         DEBIAN_FRONTEND=noninteractive apt-get -y install git cmake g++ pkg-config libusb-1.0-0-dev libxml2-dev libboost-dev libboost-exception-dev libboost-program-options-dev libboost-test-dev valgrind &&
  #         git clone https://github.com/ralovich/antpm &&
  #         cd antpm &&
  #         cmake -B build -S src -DCMAKE_BUILD_TYPE=Release -DUSE_BOOST_TEST=TRUE -DUSE_GANT=TRUE &&
  #         cmake --build build --config Release -j &&
  #         (cd build && ctest -C Release --rerun-failed --output-on-failure -j 4 --timeout 120)
  #         "
  #       platforms: linux/s390x

  # secondtry:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: secondtry
  #     run: >
  #       docker run --rm --privileged multiarch/qemu-user-static:register --reset &&
  #       docker run --rm --platform linux/s390x s390x/ubuntu:latest
  #       bash -c
  #       "uname -a &&
  #       lscpu | grep Endian &&
  #       apt-get -y update &&
  #       DEBIAN_FRONTEND=noninteractive apt-get -y install git cmake g++ pkg-config libusb-1.0-0-dev libxml2-dev libboost-dev libboost-exception-dev libboost-program-options-dev libboost-test-dev valgrind &&
  #       git clone https://github.com/ralovich/antpm &&
  #       cd antpm &&
  #       cmake -B build -S src -DCMAKE_BUILD_TYPE=Release -DUSE_BOOST_TEST=TRUE -DUSE_GANT=TRUE &&
  #       cmake --build build --config Release -j &&
  #       (cd build && ctest -C Release --rerun-failed --output-on-failure -j 4 --timeout 120)
  #       "

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Run Tests in Docker
        run: >
          docker run
          --rm
          -v $(pwd):/${{ github.workspace }}
          -w ${{ github.workspace }}
          --platform linux/s390x
          ubuntu:latest
          bash -c
          "uname -m &&
          lscpu | grep Endian &&
          apt-get -y update &&
          DEBIAN_FRONTEND=noninteractive apt-get -y install cmake g++ pkg-config libusb-1.0-0-dev libxml2-dev libboost-dev libboost-exception-dev libboost-program-options-dev libboost-test-dev valgrind &&
          cmake -B build -S src -DCMAKE_BUILD_TYPE=Release -DUSE_BOOST_TEST=TRUE -DUSE_GANT=TRUE &&
          cmake --build build --config Release -j &&
          (cd build && ctest -C Release --rerun-failed --output-on-failure -j 4 --timeout 240)
          "
